export enum ProcessType {
    filter = 'filter',
    aggregate = 'aggregate',
    data_sampling = 'data_sampling',
    field_remover = 'field_remover',
    field_renamer = 'field_renamer',
    field_selector = 'field_selector',
    hash = 'hash',
    type_converter = 'type_converter',
    join = 'join',
    replicate = 'replicate',
    csv_loader = 'csv_loader',
    csv_extractor = 'csv_extractor',
    json_extractor = 'json_extractor',
    json_loader = 'json_loader',
    math = 'math',
    data_cleanser = 'data_cleanser',
    concatenate = 'concatenate',
}

export enum customProcessType {
    filter = 'filter',
    aggregate = 'aggregate',
    data_sampling = 'data_sampling',
    field_remover = 'field_remover',
    field_renamer = 'field_renamer',
    field_selector = 'field_selector',
    hash = 'hash',
    type_converter = 'type_converter',
    join = 'join',
    replicate = 'replicate',
    math = 'math',
    data_cleanser = 'data_cleanser',
    concatenate = 'concatenate',
}
