export enum ProcessType {
    Filter = 'filter',
    Aggregate = 'aggregate',
    DataSampling = 'data_sampling',
    FieldRemover = 'field_remover',
    FieldRenamer = 'field_renamer',
    FieldSelector = 'field_selector',
    Hash = 'hash',
    TypeConverter = 'type_converter',
    Join = 'join',
    Replicate = 'replicate',
    CSVLoader = 'csv_loader',
    CSVExtractor = 'csv_extractor',
    JSONExtractor = 'json_extractor',
    JSONLoader = 'json_loader',
    Math = 'math',
}

export enum customProcessType {
    Filter = 'filter',
    Aggregate = 'aggregate',
    DataSampling = 'data_sampling',
    FieldRemover = 'field_remover',
    FieldRenamer = 'field_renamer',
    FieldSelector = 'field_selector',
    Hash = 'hash',
    TypeConverter = 'type_converter',
    Join = 'join',
    Replicate = 'replicate',
    Math = 'math',
}
